Hotfix/page styling fix
BinaryStudioAcademy/bsa-2022-tasque pull request #109
Opened 2022-08-23 17:07 UTC by goose0chka

- Header is now not scrollable
- app is always fills all the screen

2022-08-23 21:06 UTC, Its-OP requested changes

2022-08-23 21:06 UTC, Its-OP commented on frontend/src/app/components/page-without-sidebar/page-without-sidebar.component.sass
> +  z-index: 1
make the value greater. We can have other elements with changed z-index

2022-08-24 06:14 UTC, Anatolii-Ivanov approved these changes

2022-08-24 16:26 UTC, ismv approved these changes

2022-08-24 20:29 UTC, merged