59 create edit organization dialog
BinaryStudioAcademy/bsa-2022-tasque pull request #115
Opened 2022-08-24 15:37 UTC by Vadis00

- Created "edit organization" dialog
- added table "user-organization"
- edit organization button added to organization-list-item.component
- fixed sidebar, its width is 50%

2022-08-25 09:03 UTC, andpew commented on backend/Tasque.Core.WebAPI/appsettings.json
> +}
Add white space, please

2022-08-25 09:05 UTC, andpew commented on frontend/src/app/components/organization-list/organization-list.component.ts
> +}
And here too

2022-08-25 09:06 UTC, andpew commented on frontend/src/core/services/organization.service.ts
> +  delUser(
Can you write the name of the method entirely, please. It's not that long.

2022-08-25 09:08 UTC, andpew commented on frontend/src/shared/components/select-users/Models.ts
>  export enum BusinessRole {
Not sure that this entity will be enum. It can be as table in db too. Ask our coaches or QA's about it.

2022-08-25 09:10 UTC, andpii commented on frontend/src/shared/components/tasque-input/input.component.ts
> +  @Input()
Why did you change this propery to such a long syntax? I think, old way does not differ from this one. Just takes much more space.

2022-08-25 17:58 UTC, andpew approved these changes

2022-08-25 18:13 UTC, andpew requested changes
Because of database changes, you should describe these changes in our diagram in the README.md. Please, update scheme.

2022-08-26 06:42 UTC, FeloniukM approved these changes, later dismissed

2022-08-26 07:18 UTC, andpew approved these changes

2022-08-26 08:02 UTC, FeloniukM approved these changes

2022-08-26 08:20 UTC, merged