199 fix create issue modal window
BinaryStudioAcademy/bsa-2022-tasque pull request #173
Opened 2022-09-06 11:43 UTC by Vadis00

2022-09-06 12:09 UTC, andpew submitted a review, later dismissed

2022-09-07 06:08 UTC, ismv commented on frontend/src/shared/components/tasque-task-creation/task-creation.component.html
> +            <tasque-dropdown [options]="projects" formControlName="projectControl" [errorMessage]="projectErrorMessage" [invalid]="!projectControl.valid"> </tasque-dropdown>
formatting

2022-09-07 06:08 UTC, ismv commented on frontend/src/shared/components/tasque-task-creation/task-creation.component.html
> +            <tasque-dropdown [options]="issueTypes" [formControl]="issueTypeControl" [errorMessage]="issueTypeErrorMessage" [invalid]="!issueTypeControl.valid"> </tasque-dropdown>
same

2022-09-07 06:08 UTC, ismv commented on frontend/src/shared/components/tasque-task-creation/task-creation.component.html
> +            <tasque-input class="input" [formControl]="summaryControl" [errorMessage]="summaryErrorMessage" [invalid]="!summaryControl.valid"> </tasque-input>
same

2022-09-07 19:53 UTC, Its-OP requested changes

2022-09-07 19:53 UTC, Its-OP commented on frontend/src/shared/components/tasque-task-creation/task-creation.component.ts
>        return 'Description must be at less  80 characters';
At least

2022-09-07 19:53 UTC, Its-OP commented on frontend/src/shared/components/tasque-task-creation/task-creation.component.ts
>        return 'Description must be at less 5000 characters';
must not exceed

2022-09-09 07:12 UTC, closed without merging