201 backlog
BinaryStudioAcademy/bsa-2022-tasque pull request #185
Opened 2022-09-07 10:03 UTC by Vadis00

2022-09-07 20:06 UTC, Its-OP requested changes

2022-09-07 20:06 UTC, Its-OP commented on backend/Tasque.BLL/Services/TaskService.cs
>              if (task == null)
You can use `.Single` instead of checking for null

2022-09-07 20:06 UTC, Its-OP commented on backend/Tasque.BLL/Services/TaskStateService.cs
> +                .Select(s => s)
Why do we need `.Select` here ?

2022-09-07 20:06 UTC, Its-OP commented on backend/Tasque.BLL/Services/TaskStateService.cs
> +            var tasksState = await _db.TaskStates
taskState**s**

2022-09-07 20:06 UTC, Its-OP commented on backend/Tasque.BLL/Services/TaskTypeService.cs
> +                .Select(s => s)
Same as above

2022-09-07 20:06 UTC, Its-OP commented on backend/Tasque.Core.WebAPI/Controllers/BacklogController.cs
> +        [HttpGet("getBacklogTasks/{projectId}")]
'backlogTasks' would be enough

2022-09-07 20:06 UTC, Its-OP commented on frontend/src/app/components/backlog/sprint/sprint.component.ts
> -  //+++++++++++++++++++++++++rewrite after the backend part of sprintі sorting is implemented++++++++++++++++
Use TODO, so we can find it easily later

2022-09-07 20:06 UTC, Its-OP commented on frontend/src/app/components/complete-sprint/complete-sprint-dialog/complete-sprint-dialog.component.html
> +            <span class="selection">{{ complatedIssues() }}</span> complated
compl**e**ted

2022-09-08 08:31 UTC, Its-OP approved these changes

2022-09-08 08:35 UTC, Anatolii-Ivanov approved these changes

2022-09-08 08:36 UTC, merged