37 create login page
BinaryStudioAcademy/bsa-2022-tasque pull request #34
Opened 2022-08-10 19:30 UTC by oleksandr-vovk

For using login dialog declare login service and write "loginService.openLoginDialog()"

2022-08-10 21:46 UTC, goose0chka requested changes

2022-08-10 21:46 UTC, goose0chka commented on frontend/src/shared/components/login-page/login-page.component.html
> +                                placeholder="Enter your email"
wrong placeholder

2022-08-11 06:38 UTC, oleksandr-vovk commented on frontend/src/shared/components/login-page/login-page.component.html
> +                                placeholder="Enter your email"
fixed

2022-08-11 06:57 UTC, Anatolii-Ivanov approved these changes

2022-08-11 07:24 UTC, goose0chka approved these changes

2022-08-11 07:55 UTC, merged