19 create button base component
BinaryStudioAcademy/bsa-2022-tasque pull request #8
Opened 2022-08-08 13:42 UTC by Vadis00

Button example:

```
-   <app-button text="Sign In" class="btn"></app-button>
-   <app-button text="Sign In" class="btn disabled"></app-button>
-   <app-button text="Create Account" class="btn mini"></app-button>
-   <app-button text="Create Account" class="btn mini disabled"></app-button>
-   <app-button text="Create Account" class="btn stroke"></app-button>
-   <app-button text="Create Account" class="btn stroke disabled"></app-button>
-   <app-button text="Create Account" class="btn fill"></app-button>
-   <app-button text="Create Account" class="btn fill disabled"></app-button>
```

2022-08-08 14:06 UTC, FeloniukM commented on frontend/src/app/component/button/button.component.html
> +</button>
Must be white space

2022-08-08 14:06 UTC, FeloniukM commented on frontend/src/app/component/button/button.component.sass
> +        cursor: not-allowed
same

2022-08-08 14:34 UTC, Vadis00 commented on frontend/src/app/component/button/button.component.html
> +</button>
done

2022-08-08 14:46 UTC, FeloniukM submitted a review, later dismissed

2022-08-08 18:30 UTC, ismv requested changes
Please pull the dev updates and use color scheme for all the colors you added

2022-08-09 08:00 UTC, ismv approved these changes

2022-08-09 08:01 UTC, FeloniukM approved these changes

2022-08-09 08:02 UTC, merged